hosts: ["HOST1", "HOST2"]
user: 'USERNAME'
branch: 'DEFAULT_BRANCH'
password: 'PASSWORD_DUH'
tomcat_user: 'TOMCAT_USERNAME'
hipchat: 'HIPCHAT_WEB_HOOK'
reviewer : ["PR_REV1", "PR_REV2"]
dev_name: 'YOUR_NAME'
folder: 'FOLDER_PATH'
log_folder: 'LOG_FOLDER_PATH'
